AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  serverlessHandsOn:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: handler.api
      Runtime: nodejs6.10
      Description: ''
      MemorySize: 128
      Timeout: 15
      Role:
        'Fn::Sub': 'arn:aws:iam::${AWS::AccountId}:role/ServerlessHandsOnRole'
      Events:
        LambdaMicroservice:
          Type: Api
          Properties:
            Path: '/{proxy+}'
            Method: ANY
  serverlessHandsOnPermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName:
        'Fn::GetAtt':
          - serverlessHandsOn
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        'Fn::Sub': 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:*/*/*/*'